version: '3'

services:
  db:
    image: spartakode/sqlite3:latest
  linkshorter:
    build: ""
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/linkshorter
    ports:
      - "8000:8000"
    depends_on:
      - db