# Generated by Django 3.2.3 on 2021-05-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('full_url', models.URLField(verbose_name='Полная ссылка')),
                ('short_url', models.URLField(verbose_name='укороченная ссылка')),
            ],
        ),
    ]
