# Generated by Django 3.2.3 on 2021-05-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shorter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.URLField(verbose_name='Укороченная ссылка'),
        ),
    ]
